**Task 1**

In [11]:
import numpy as np

lst = [2, 6, 11, 24, 8, 45, 25, 60]

# Delete last element
lst.pop()
print("After deleting last element:", lst)

# Add 22 at index 3
lst.insert(3, 22)
print("After inserting 22 at index 3:", lst)

# Create ndarray
arr = np.array(lst)
print("ndarray array:", arr)


After deleting last element: [2, 6, 11, 24, 8, 45, 25]
After inserting 22 at index 3: [2, 6, 11, 22, 24, 8, 45, 25]
ndarray array: [ 2  6 11 22 24  8 45 25]


**Task 2**

In [16]:
A2d = np.arange(12).reshape(6, 2)
print("2D Array:\n", A2d)

A3d = np.arange(18).reshape(2, 3, 3)
print("3D Array:\n", A3d)

split_arr = np.split(A2d, 3)
print("Splitted Arrays:")
print("Array 1 \n",split_arr[0])
print("Array 1 \n",split_arr[1])
print("Array 1 \n",split_arr[2])

2D Array:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
3D Array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
Splitted Arrays:
Array 1 
 [[0 1]
 [2 3]]
Array 1 
 [[4 5]
 [6 7]]
Array 1 
 [[ 8  9]
 [10 11]]


**Task 3**

In [8]:
A = np.array([2, 6, 11, 24, 8, 45, 25, 60])
even_indexes = np.where(A % 2 == 0)
print("Indexes of even values:", even_indexes)


Indexes of even values: (array([0, 1, 3, 4, 7]),)


**Task 4**

In [17]:
A = np.array([2, 6, 11, 24, 8, 45, 25, 60])
filter_arr = A[A > 55]
print("Values greater than 55:", filter_arr)


Values greater than 55: [60]


**Task 5**

In [21]:
matrix = np.arange(2, 11).reshape(3, 3)
print("Matrix:\n", matrix)

matrix_float = matrix.astype(float)
print("Float Matrix:\n", matrix_float)

flat = matrix_float.flatten()
print("Flattened array:", flat)
print("Max value:", np.max(flat))
print("Min value:", np.min(flat))


Matrix:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Float Matrix:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Flattened array: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Max value: 10.0
Min value: 2.0


**Task 6**

In [22]:
A = np.random.randint(0, 100, size=150)
print("Random array of 150 integers:\n", A)

even_values = A[A % 2 == 0]
print("\nEven values from the array:\n", even_values)
num_even = len(even_values)
print("Number of even values:", num_even)

odd_values = A[A % 2 != 0]
print("\nOdd values from the array:\n", odd_values)
num_odd = len(odd_values)
print("Number of odd values:", num_odd)

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_values = A[np.vectorize(is_prime)(A)]

print("\nPrime values from the array:\n", prime_values)
print("Number of prime values:", len(prime_values))


def print_multiples_from_array(n, array):
  print(f"Multiples of {n} found in the array:")
  multiples_in_array = array[array % n == 0]
  if len(multiples_in_array) > 0:
    for multiple in multiples_in_array:
      print(multiple)
  else:
    print(f"No multiples of {n} found in the array.")
print_multiples_from_array(5, A)


Random array of 150 integers:
 [17 66 33 87  5 31 75 79 63 22 21 53 97 53 31 93 38 66 36 72 98 53  9 82
 38 23 39 42 90 21 62 74 52 76 63 92 66 78 10 19 59 13 21 53  8 30 12  4
 80 30 49 58 66 98 41 39 30 83 58 61  1 47 42 98 69 45 51 83 56 72 17 65
 45 27 39 11 18 82 62 91 41 24 37  8 86 45 53 79 10 56 76 87 91 33 31 28
 76 62 50 97 86 90  2 20 70 49 52 19 90 43 24 45  5 50 55  2 16 44 85 84
 28 98 10 15 38 16 31 24 45 84 19 36 26 10 40 55 17 70 51  2 68  2 57 39
 65 94 26 74 38 85]

Even values from the array:
 [66 22 38 66 36 72 98 82 38 42 90 62 74 52 76 92 66 78 10  8 30 12  4 80
 30 58 66 98 30 58 42 98 56 72 18 82 62 24  8 86 10 56 76 28 76 62 50 86
 90  2 20 70 52 90 24 50  2 16 44 84 28 98 10 38 16 24 84 36 26 10 40 70
  2 68  2 94 26 74 38]
Number of even values: 79

Odd values from the array:
 [17 33 87  5 31 75 79 63 21 53 97 53 31 93 53  9 23 39 21 63 19 59 13 21
 53 49 41 39 83 61  1 47 69 45 51 83 17 65 45 27 39 11 91 41 37 45 53 79
 87 91 33 31 97 49 19 43 45  5 55 85 1